/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bountyhunter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        if(classUnderTest == null) {
            System.out.println("classUnderTest is null");
        }
        else {
            System.out.println("classUnderTest is not null");
        }
    }
}
